config/routes.rb
Rails.application.routes.draw do
  resources :scrape_results
  root :to => 'scrape_results#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scrape_result.rb
class ScrapeResult < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/scrape_results_controller.rb
class ScrapeResultsController < ApplicationController
  before_action :set_scrape_result, only: [:show, :edit, :update, :destroy]

  # GET /scrape_results
  # GET /scrape_results.json
  def index
    @scrape_result = ScrapeResult.new
    @scrape_results = ScrapeResult.paginate(page: params[:page], per_page: 1).order('id DESC')
  end

  # GET /scrape_results/1
  # GET /scrape_results/1.json
  def show
  end

  # GET /scrape_results/new
  def new
    @scrape_result = ScrapeResult.new
  end


  # POST /scrape_results
  # POST /scrape_results.json
  def create
    scraped_data = {}
    url_regex = /^(?:https?:\/\/)?([a-z0-9+.-]+\.[a-z]{2,})(?:\/|\?|'|"|:|&|\s|,|`|#|~|}|$)/i
    web_site = scrape_result_params[:web_site].match(url_regex).captures[0] rescue nil
    @scrape_result = nil
    if web_site.present?
      begin
        scraped_data = BrilliantWebScraper.new(web_site)
      rescue StandardError => e
        scraped_data = {error: e.message}
      end
      if scraped_data[:error].nil?
        @scrape_result = ScrapeResult.find_by(web_site: web_site)
        if @scrape_result.present?
           @scrape_result.update_attributes(results: scraped_data)
          @scrape_result = ScrapeResult.find_by(web_site: web_site)
        else
          @scrape_result = ScrapeResult.new(web_site: web_site, results: scraped_data)
        end
      else
        @scrape_result = ScrapeResult.new
        @scrape_result.errors.add(:base, scraped_data[:error])
      end
    else
      @scrape_result = ScrapeResult.new(web_site: web_site, results: scraped_data)
      @scrape_result.errors.add(:base, 'Invalid Website URL.')
    end
    respond_to do |format|
      if @scrape_result.errors.none? && @scrape_result.save
        format.html { redirect_to @scrape_result, notice: 'Website was successfully scraped.' }
        format.json { render :show, status: :created, location: @scrape_result }
      else
        flash[:notice] =  @scrape_result.errors[:base].first
        format.html { redirect_to root_path }
        format.json { render json: @scrape_result.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scrape_result
      @scrape_result = ScrapeResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scrape_result_params
      params.require(:scrape_result).permit(:web_site, :results)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrape_results_helper.rb
module ScrapeResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScraperDemo</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scrape_results/_form.html.erb
<%= form_for(scrape_result, :html => {:class => "form-inline"}) do |f| %>
  <% if scrape_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scrape_result.errors.count, "error") %> prohibited this scrape_result from being saved:</h2>

      <ul>
      <% scrape_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :web_site, required: true, class: 'form-control', placeholder: "Website URL" %>
  </div>

  <div class="actions">
    <%= f.submit "Scrape Website", type: "submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/scrape_results/edit.html.erb
<h1>Editing Scrape Result</h1>

<%= render 'form', scrape_result: @scrape_result %>

<%= link_to 'Show', @scrape_result %> |
<%= link_to 'Back', scrape_results_path %>

app/views/scrape_results/index.html.erb
<%= form_for(@scrape_result, :html => {:class => "form-inline"}) do |f| %>
  <% if @scrape_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scrape_result.errors.count, "error") %> prohibited this scrape_result from being saved:</h2>

      <ul>
      <% @scrape_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :web_site, required: true, class: 'form-control',  placeholder: "example.com" %>
  </div>

  <div class="actions">
    <%= f.submit "Scrape website", type: "submit", class: "btn btn-primary" %>
  </div>
<% end %>
  <% if notice %>
  
  <p class="alert alert-warning alert-dismissible fade show" role="alert"><%= notice %></p>
  <% end %>
  <%= will_paginate(@scrape_results, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="row">WebSite</th>
      <th scope="col">Scrape Results</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @scrape_results.each do |scrape_result| %>
      <tr>
        <td scope="col"><pre><h6><%= link_to scrape_result.web_site, scrape_result %></h6></pre></td>
        <td scope="row"><pre><%= JSON.pretty_generate(scrape_result.results)
        %><pre></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/scrape_results/new.html.erb
<h1> Scrape a website</h1>

<%= render 'form', scrape_result: @scrape_result %>

<%= link_to 'Back', root_url, class: 'btn btn-default', role: 'button' %>

app/views/scrape_results/show.html.erb
<p class="alert alert-success" role="alert"><%= notice %></p>

<%= link_to '<--Back', scrape_results_path, class: "btn btn-link" %>

<h4><%= @scrape_result.web_site %></h4>

<p>
  <pre> <%= JSON.pretty_generate(@scrape_result.results)%></pre>
</p>